version: "3.8"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: php-tut-nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:80
    volumes:
      - ./src:/var/www/html
      - ./scripts/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      php-tut:
        ipv4_address: 172.16.79.2

  mysql:
    image: mysql:8.0
    container_name: php-tut-mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT_OUT}:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      php-tut:
        ipv4_address: 172.16.79.39
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  #redis:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-tut-app
    restart: unless-stopped
    tty: true
    ports:
      - 9000:9000
      - 5678:5678 # For debugging
    volumes:
      - ./src:/var/www/html
    networks:
      php-tut:
        ipv4_address: 172.16.79.69
    depends_on:
      - nginx
      - mysql
      #- redis

volumes:
  data:

networks:
  php-tut:
    ipam:
      driver: default
      config:
        - subnet: 172.16.79.0/16
          gateway: 172.16.79.1
  