version: "3.8"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: php-tut-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./scripts/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0
    container_name: php-tut-mysql
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: phptut
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: php_tut

  #redis:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-tut-app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - nginx
      - mysql
      #- redis

volumes:
  data: